#!/bin/bash
#
# DWM Autostart
# Put all applications you want to start here
# I don't suggest starting another shellscripts under this, they clutter pstree
#
# When you execeute another process, if the parent dies, child becomes a root,
# so you can easily get zombie processes. I suggest debugging your autostart with pstree.
#
# Autostart can be anything that is executable, but we are using bash as example here,
# note that other shell scripts are sourced instead of executed.
#

# Make GTK apps look and behave how they were set up in the gnome config tools
if test -x /usr/libexec/gnome-settings-daemon >/dev/null; then
  /usr/libexec/gnome-settings-daemon &
elif which gnome-settings-daemon >/dev/null 2>&1; then
  gnome-settings-daemon &
# Make GTK apps look and behave how they were set up in the XFCE config tools
elif which xfce-mcs-manager >/dev/null 2>&1; then
  xfce-mcs-manager n &
fi
# Preload stuff for KDE apps
if which start_kdeinit >/dev/null 2>&1; then
  LD_BIND_NOW=true start_kdeinit --new-startup +kcminit_startup &
fi

# Run XDG autostart things.  By default anything desktop-specific
# See xdg-autostart --help more info
DESKTOP_ENV="xfce"
if which /usr/lib/openbox/xdg-autostart >/dev/null 2>&1; then
  /usr/lib/openbox/xdg-autostart $DESKTOP_ENV
fi

# Turn off dmps and screen blanking
xset -dpms
xset s off

# DWM text
xsetroot -name "DWM"

# Start ssh_watch
ssh_watch &

# Wait for WM a bit
sleep 5

# Set wallpapers
(nitrogen --restore &> /dev/null) &

# Networkmanager applet
(nm-applet &> /dev/null) &

# Clipit
(clipit &> /dev/null) &

# Smart notify
(smart-notifier &> /dev/null) &

# Dropbox
(dropboxd &> /dev/null) &

# Conky
(conky -q -c $HOME/.config/conky/db.conky &> /dev/null) &

# Xcompmgr
(xcompmgr -fF -I-.02 -O-.04 -D0001 &> /dev/null) &

# Dzen
source "$HOME/.config/dwm/dzen2start"

# RSS
RSS

# Torrent
TORRENT

# IRC
IRC

# Redshift
(sleep 10 && gtk-redshift -l 62:22 &> /dev/null) &

# Cow notify
(sleep 10 && cow-notify &> /dev/null) &

# Hatsune Miku
(sleep 10 && macopix --sockmsg ~/.config/macopix/L-Miku.mcpx &> /dev/null) &

# IMPORTANT!
# Avoids this script from exiting until DWM finishes
# Do this for all parent shell scripts too.
# Use pstree to debug your autostart
# note: it's possible to find DWM's PID by other means,
# but bash provides it out of the box neatly
while kill -0 $PPID; do
   OS=`df / | awk '{print $5}' | tail -n 1`;
   STORAGE=`df /media/Storage | awk '{ print $5 }' | tail -n 1`;
   ANIME=`df /media/Anime | awk '{ print $5 }' | tail -n 1`;
   NOTE=`shuf -n 1 "$HOME/.note"`
   xsetroot -name "$(echo -e "\x05$NOTE \x02|\x01 OS $OS :: STORAGE $STORAGE :: ANIME $ANIME \x02|\x01 >> $(grep ^Dirty /proc/meminfo | sed 's/^Dirty: *//')")"
   sleep 10;
done

# Exit
# If you get any processes that run even after logout, kill them here
killall redshift
killall opera
deadbeef --quit    # Deadbeef fails saving playlist on exit without this
killall ssh_watch
