#!/bin/bash

# Settings
SLEEP=1
ICONPATH=$HOME/.icons/dwm

# Settings that don't need to update every loop
TIMEOUT_NP=10
TIMEOUT_LOAD=5
TIMEOUT_PACMAN=300
TIMEOUT_TEMP=5

# Counters
PM_CYCLES=0
NP_CYCLES=0
LO_CYCLES=0
TEMP_CYCLES=0

# Start values
UPDATES="$(pacman -Qu | wc -l)"
LOAD="$(uptime | cut -d, -f 3 |  awk -F: ' $2>0.1 { a=$2;printf ("%4.2f",a) }')"
NP="$(np)"
LINUX="$(uname -srm)"
CPU_TEMP=(0,0,0,0)
GPU_TEMP=0

function np_update()
{
   ((NP_CYCLES++))
   [[ $NP_CYCLES -eq $TIMEOUT_NP ]] || return

   NP="$(np)"
   NP_CYCLES=0
}

function load_update()
{
   ((LO_CYCLES++))
   [[ $LO_CYCLES -eq $TIMEOUT_LOAD ]] || return

   LOAD="$(uptime | cut -d, -f 3 |  awk -F: ' $2>0.1 { a=$2;printf ("%4.2f",a) }')"
   LO_CYCLES=0
}

function pacman_update()
{
   ((PM_CYCLES++))
   [[ $PM_CYCLES -eq $TIMEOUT_PACMAN ]] || return

   UPDATES="$(pacman -Qu | wc -l)"
   PM_CYCLES=0
}

function temp_update()
{
   ((TEMP_CYCLES++))
   [[ $TEMP_CYCLES -eq $TIMEOUT_TEMP ]] || return

   for i in $(seq 0 3); do
      CPU_TEMP[$i]="$(sensors | grep Core\ $i| paste -s | cut -c16-17,17-17)"
   done
   GPU_TEMP="$(nvidia-settings -query GPUCoreTemp | perl -ne 'print $1 if /GPUCoreTemp.*?: (\d+)./;')"

   TEMP_CYCLES=0
}

while true; do
   TIME="$(date "+%a %d.%m.%Y %H:%M:%S")"
   load_update
   np_update
   temp_update
   pacman_update

   # Linux info
   echo -n "^fg(white)^i(${ICONPATH}/arch.xbm) ${LINUX}^fg() "
   echo -n "^fg(red3)^i(${ICONPATH}/cpu.xbm)^fg(white) ${LOAD} "

   # Time
   echo -n "^fg(black3)^i(${ICONPATH}/clock.xbm)^fg(white) ${TIME} "

   # Pacman info
   echo -n "^fg(yellow3)^i(${ICONPATH}/pacman.xbm)^fg(white) "
   if [[ "$UPDATES" ]]; then
      echo -n "${UPDATES} updates "
   else
      echo -n "no updates.. "
   fi

   # CPU info
   for i in $(seq 0 3); do
      echo -n "^fg(#80AA83)^i(${ICONPATH}/cpu.xbm)$i^fg(white) ${CPU_TEMP[$i]}°C "
   done

   # GPU info
   [[ ! "$GPU_TEMP" ]] || echo -n "^fg(orange3)^i(${ICONPATH}/cpu.xbm)^fg(white) ${GPU_TEMP}°C "

   # Now playing
   [[ ! "$NP" ]] || echo -n "^fn(IPAMonaGothic:size=7)^fg(black3)^i(${ICONPATH}/play.xbm)^fg(white) ${NP}^fn() "

   # Finish
   echo ""
   sleep ${SLEEP}
done;
