#!/bin/bash

# Dzen
RAM_DWIDTH=100
RAM_WIDTH=120
WLAN_DWIDTH=200
WLAN_WIDTH=170
GMAIL_WIDTH=150
GMAIL_DWIDTH=420
HEIGHT=10
POSY=1024

FONT="erusfont:size=9"
RAM_ACT='entertitle=uncollapse;leavetitle=collapse'
WLAN_ACT='entertitle=uncollapse;leavetitle=collapse'
GMAIL_ACT='entertitle=uncollapse;leavetitle=collapse'

ETC_WIDTH=$((${WLAN_WIDTH}+${GMAIL_WIDTH}+${RAM_WIDTH}))
WIDTH=$((1440-${ETC_WIDTH}))
RAM_X=$WIDTH
GMAIL_X=$((${RAM_X}+${RAM_WIDTH}))
WLAN_X=$((${GMAIL_X}+${GMAIL_WIDTH}))

(~/.config/dwm/bottom | dzen2 -ta l -h $HEIGHT -fn "$FONT" -x 0 -y $POSY -w $WIDTH -tw $WIDTH -e "") &
(~/.config/dwm/gmail  | dzen2 -ta l -l 5 -h $HEIGHT -fn "$FONT" -x $GMAIL_X -y $POSY -tw $GMAIL_WIDTH -w $GMAIL_DWIDTH -e "$GMAIL_ACT") &
(~/.config/dwm/rambar | dzen2 -ta l -l 3 -h $HEIGHT -fn "$FONT" -x $RAM_X -y $POSY -w $RAM_DWIDTH -tw $RAM_WIDTH -sa c -e "$RAM_ACT") &
(~/.config/dwm/wlan   | dzen2 -ta l -l 5 -h $HEIGHT -fn "$FONT" -x $WLAN_X -y $POSY -tw $WLAN_WIDTH -w $WLAN_DWIDTH -e "$WLAN_ACT") &
