#!/bin/bash
ICONPATH=$HOME/.icons/dwm

AWKS='/MemTotal/   {mtotal=$2};
/MemFree/    {mfree=$2};
/Active/     {mactive=$2};
/^Cached/     {mcached=$2};
/SwapTotal/  {swtotal=$2};
/SwapFree/   {swfree=$2};
END {
    print mactive " " mtotal;
    print mactive " " mtotal;
    print mcached " " mtotal;
    print swtotal-swfree " " swtotal; }'

MEMACTIVE=$(printf "%4d" $(echo "0"))
while echo "^tw()^fg(red3)^i(${ICONPATH}/mem.xbm)^fg(white) ${MEMACTIVE}MiB
Active
Cached
Swap  " | paste -d ' ' - <(awk "$AWKS" /proc/meminfo | gdbar -fg '#d00e0e' -bg '#37383a' -w 50 -h 7); do
MEMACTIVE=$(printf "%4d" $(echo "`awk '/Active:/{print $2}' /proc/meminfo`/1024" | bc))
sleep 5
done
