#!/bin/bash
ICONPATH=$HOME/.icons/dwm

AWKS='/MemTotal/   {mtotal=$2};
/MemFree/    {mfree=$2};
/Active/     {mactive=$2};
/^Cached/     {mcached=$2};
/SwapTotal/  {swtotal=$2};
/SwapFree/   {swfree=$2};
END {
    print mtotal-mfree " " mtotal;
    print mactive " " mtotal;
    print mcached " " mtotal;
    print swtotal-swfree " " swtotal; }'

    while echo "^tw()^fg(red3)^i(${ICONPATH}/mem.xbm)^fg()
Active
Cached
Swap  " | paste -d ' ' - <(awk "$AWKS" /proc/meminfo | gdbar -fg '#d00e0e' -bg '#37383a' -w 50 -h 7); do
sleep 5
done
