#!/bin/bash

wid=$(xdotool search --classname URxvtq)
if [ -z "$wid" ]; then
  sh ~/.config/dwm/urxvtc -name URxvtq -geometry 238x26+0+134 -borderLess
  wid=$(xdotool search --classname URxvtq | head -1)
  xdotool windowfocus $wid
else
  if [ -z "$(xdotool search --onlyvisible --classname URxvtq 2>/dev/null)" ]; then
    xdotool windowmap $wid
    xdotool windowfocus $wid
    xdotool windowraise $wid
  else
    xdotool windowunmap $wid
  fi
fi
