#!/bin/bash
#
# (c) 2007, by Robert Manea
# (c) 2007, Christian Dietrich

# icons
ICONPATH=$HOME/.icons/dwm
# network interface
INTERFACE=wlan0
WIRELESS=1

# update every x seconds
SLEEP=1
BBG='#333' # Bar Background
BFG=green  # Bar Foreground

# Here we remember the previous rx/tx counts
RXB=`cat /sys/class/net/${INTERFACE}/statistics/rx_bytes`
TXB=`cat /sys/class/net/${INTERFACE}/statistics/tx_bytes`

while true; do
   # get new rx/tx counts
   RXBN=`cat /sys/class/net/${INTERFACE}/statistics/rx_bytes`
   TXBN=`cat /sys/class/net/${INTERFACE}/statistics/tx_bytes`

   # calculate the rates
   # format the values to 4 digit fields
   RXR=$(printf "%4d\n" $(echo "($RXBN - $RXB) / 1024/${SLEEP}" | bc))
   TXR=$(printf "%4d\n" $(echo "($TXBN - $TXB) / 1024/${SLEEP}" | bc))

   if [[ "$WIRELESS" ]]; then
      SIGNAL=$(iwconfig $INTERFACE | sed -ne '/Link Quality/ { s/.*Link Quality=\([0-9]*\)\/\([0-9]*\).*/\1/p}' )
      SIGNALMETER=`echo $SIGNAL | gdbar -s v -h 15 -ss 1 -sh 2 -sw 4 -fg $BFG -bg $BBG -nonl`
   fi

   # print out the rates with some nice formatting
   echo "^fg(#80AA83)^p(3)^i(${ICONPATH}/net_down_03.xbm)^fg(white)${RXR}KiB/s ^fg(orange3)^i(${ICONPATH}/net_up_03.xbm)^fg(white)${TXR}KiB/s^fg() $SIGNALMETER"

   # reset old rates
   RXB=$RXBN; TXB=$TXBN

   sleep $SLEEP
done
