#!/bin/bash

wid=$(xdotool search --classname urxvtq)
if [ -z "$wid" ]; then
  sh ~/.config/openbox/urxvtc -name urxvtq -geometry 240x26+0+124 -borderLess -depth 32
  wid=$(xdotool search --classname urxvtq | head -1)
  xdotool windowfocus $wid
else
  if [ -z "$(xdotool search --onlyvisible --classname urxvtq 2>/dev/null)" ]; then
    xdotool windowmap $wid
    xdotool windowfocus $wid
  else
    xdotool windowunmap $wid
  fi
fi